Set up rubocop for travis
everypolitician-scrapers/hong_kong_legislative_council_members pull request #4
Opened 2017-04-24 15:27 UTC by ondenman

This PR is in preparation of refactoring the scraper to use `scraped` (WIP: )

This enables Travis to run rubocop checks against PRs.

Note: I have not enabled Travis as the current code will not pass.

2017-04-24 15:47 UTC, tmtmtmtm requested changes

2017-04-24 15:47 UTC, tmtmtmtm commented on .rubocop-https---raw-githubusercontent-com-everypolitician-everypolitician-data-master--rubocop-base-yml
> +# http://rubocop.readthedocs.io/en/latest/configuration/#inheriting-configuration-from-a-remote-url
Looks like you checked this in by mistake…

2017-04-24 16:15 UTC, tmtmtmtm requested changes
```
> bundle exec rake   
rake aborted!
Don't know how to build task 'rubocop' (see --tasks)
```

2017-04-24 16:24 UTC, tmtmtmtm requested changes
> Note: I have not enabled Travis as the current code will not pass.

We shouldn't be merging code that fails `bundle exec rake`. This isn't about whether it fails *on travis* — travis is a way automating that check.

2017-04-24 16:27 UTC, ondenman commented
> We shouldn't be merging code that fails `bundle exec rake`. This isn't about whether it fails *on travis* — travis is a way automating that check. 

@tmtmtmtm Should I cherry pick these across to #3 then?

2017-04-25 07:48 UTC, tmtmtmtm commented
@ondenman I've run my semi-automatic moderniser as https://github.com/everypolitician-scrapers/hong_kong_legislative_council_members/pull/5

2017-04-25 07:48 UTC, closed without merging